### ISSUE TITLE
Admin Key?

### ISSUE THREAD

**Issue by johnny2678** [Thoroslives/immich_remove_offline_files#1]
Sorry for the super dumb question - I see where to get my user API key from Immich.  Where do I get the Admin Key?  I searched the immich docs but could only find the user API key instructions.

**Comment by Thoroslives** [comment]
> Sorry for the super dumb question - I see where to get my user API key from Immich. Where do I get the Admin Key? I searched the immich docs but could only find the user API key instructions.

So thats the same process but on the Admin account

**Comment by johnny2678** [comment]
so if I am the admin, do I just use the same key for both the admin key and the user key?

**Comment by johnny2678** [comment]
> so if I am the admin, do I just use the same key for both the admin key and the user key?

yea, that didn't work.  results in a log full of:
```
Failed to delete asset d682244a-4429-4b1c-a176-eb476dc72b57 due to potential API key mismatch. Ensure you're using the asset owners API key as the User API key.
```

**Comment by Thoroslives** [comment]
> > so if I am the admin, do I just use the same key for both the admin key and the user key?
> 
> yea, that didn't work. results in a log full of:
> 
> ```
> Failed to delete asset d682244a-4429-4b1c-a176-eb476dc72b57 due to potential API key mismatch. Ensure you're using the asset owners API key as the User API key.
> ```

If you are the owner of the assets yes, but if youre not you will need to use the owners api
