### ISSUE TITLE
where do you get the admin api key? 

### ISSUE THREAD

**Issue by joey-suri** [Thoroslives/immich_remove_offline_files#3]
I am getting this output when i respond yes.

Failed to delete asset //////////////// due to potential API key mismatch. Ensure you're using the asset owners API key as the User API key.

I am using the API key from the admin account...

**Comment by Thoroslives** [comment]
Do the assets you are trying to delete belong to the admin user. 
The script requires the admin API to search and return orphaned assets, but requires the owners (the user) API for deletion.

**Comment by joey-suri** [comment]
I’m using the api key from the admin account and the assets belong to the
admin user… am I missing something ? The api key for admin I get from my
account that is the admin user correct?

**Comment by Thoroslives** [comment]
Correct, you will have to enter it twice.

**Comment by joey-suri** [comment]
Thats what I did, it gets the error listed but it seems to be working because the repair page no longer shows the missing content.
